import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "@/lib/api";
import { PageHeader, Card, StatCard } from "@/components/Common";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

const money = (n) => `₹${Number(n || 0).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;
const nowMonth = new Date().toISOString().slice(0, 7);
function Table({ title, rows, columns }) { return <Card className="overflow-x-auto"><div className="p-4 font-display font-semibold">{title}</div><table className="data-table w-full"><thead><tr>{columns.map(([, label]) => <th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map((r, i) => <tr key={i}>{columns.map(([key]) => <td key={key}>{typeof r[key] === "number" ? money(r[key]) : (r[key]?.slice?.(0, 10) || r[key] || "—")}</td>)}</tr>)}{!rows.length && <tr><td colSpan={columns.length} className="py-6 text-center text-slate-500">No transactions for this period.</td></tr>}</tbody></table></Card>; }

export default function Accounts() {
  const [customers, setCustomers] = useState([]), [fabricators, setFabricators] = useState([]), [suppliers, setSuppliers] = useState([]), [workers, setWorkers] = useState([]);
  const [partyType, setPartyType] = useState("CUSTOMER"), [partyId, setPartyId] = useState(""), [month, setMonth] = useState(nowMonth), [ledger, setLedger] = useState(null);
  const [amount, setAmount] = useState(""), [mode, setMode] = useState("UPI"), [reference, setReference] = useState(""); const [view, setView] = useState("ledger"), [book, setBook] = useState(null), [expenses, setExpenses] = useState([]), [outstanding, setOutstanding] = useState([]);
  const [entryKind, setEntryKind] = useState("PAYMENT_RECEIVED"), [entryDate, setEntryDate] = useState(new Date().toISOString().slice(0, 10)), [entryNotes, setEntryNotes] = useState("");
  const lists = { CUSTOMER: customers, FABRICATOR: fabricators, SUPPLIER: suppliers, WORKER: workers }, parties = lists[partyType] || [];
  const loadLedger = () => partyId && api.get(`/accounts/party-ledger?party_id=${partyId}&party_type=${partyType}&month=${month}`).then(setLedger).catch(() => setLedger(null));
  useEffect(() => { Promise.all([api.get("/customers"), api.get("/fabricators"), api.get("/suppliers").catch(() => []), api.get("/workers")]).then(([c, f, s, w]) => { setCustomers(c); setFabricators(f); setSuppliers(s); setWorkers(w); setPartyId(c[0]?.id || ""); }); }, []);
  useEffect(() => { loadLedger(); }, [partyId, partyType, month]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (view === "daybook") api.get(`/accounts/day-book?month=${month}`).then(setBook).catch(() => setBook([])); if (["cash", "bank", "upi"].includes(view)) api.get(`/accounts/books/${view}?month=${month}`).then(setBook).catch(() => setBook(null)); if (view === "expenses") api.get(`/accounts/expenses?month=${month}`).then(setExpenses).catch(() => setExpenses([])); if (view === "outstanding") api.get(`/accounts/outstanding?month=${month}`).then(setOutstanding).catch(() => setOutstanding([])); }, [view, month]);
  const changeType = (type) => { setPartyType(type); setPartyId((lists[type] || [])[0]?.id || ""); };
  const submit = async (kind) => { await api.post("/accounts/transactions", { party_id: partyId, party_type: partyType, kind, amount: Number(amount), transaction_date: `${month}-01`, payment_mode: mode, reference_no: reference }); setAmount(""); setReference(""); loadLedger(); };
  const submitDaily = async () => { if (entryKind === "EXPENSE") await api.post("/accounts/expenses", { expense_date: entryDate, category: entryNotes || "Miscellaneous", classification: "FACTORY_OVERHEAD", amount: Number(amount), vendor_id: partyId, payment_mode: mode, invoice_no: reference, notes: entryNotes }); else await api.post("/accounts/transactions", { party_id: partyId, party_type: partyType, kind: entryKind, amount: Number(amount), transaction_date: entryDate, payment_mode: mode, reference_no: reference, notes: entryNotes }); setAmount(""); setReference(""); setEntryNotes(""); setView("daybook"); };
  const tabs = [["daily", "Add Daily Transaction"], ["ledger", "Ledgers"], ["daybook", "Day Book"], ["cash", "Cash Book"], ["bank", "Bank Book"], ["upi", "UPI Book"], ["expenses", "Expenses"], ["outstanding", "Outstanding"]];
  return <div data-testid="accounts-page"><PageHeader title="Accounts" subtitle="Transaction-driven finance, ledgers and books" actions={<Button variant="outline" asChild><Link to="/accounts/article-costing">Article Costing</Link></Button>} /><div className="flex flex-wrap gap-2 mb-5">{tabs.map(([id, label]) => <Button key={id} size="sm" variant={view === id ? "default" : "outline"} onClick={() => setView(id)}>{label}</Button>)}</div>
    {view !== "ledger" && <Card className="p-3 mb-5"><Input className="w-44" type="month" value={month} onChange={e => setMonth(e.target.value)} /></Card>}
    {view === "daily" && <Card className="p-4"><div className="font-display font-semibold mb-1">Add Daily Transaction</div><p className="text-xs text-slate-500 mb-4">Post a receipt, payment, advance, adjustment, credit note or expense once. It will appear in the ledger and the relevant daily book.</p><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><Input type="date" value={entryDate} onChange={e => setEntryDate(e.target.value)} /><select className="border rounded px-3" value={partyType} onChange={e => changeType(e.target.value)}><option value="CUSTOMER">Customer</option><option value="SUPPLIER">Supplier</option><option value="FABRICATOR">Fabricator</option><option value="WORKER">Worker</option></select><select className="border rounded px-3" value={partyId} onChange={e => setPartyId(e.target.value)}>{parties.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><select className="border rounded px-3" value={entryKind} onChange={e => setEntryKind(e.target.value)}>{["PAYMENT_RECEIVED", "PAYMENT", "ADVANCE", "ADJUSTMENT", "CREDIT_NOTE", "DEBIT_NOTE", "EXPENSE"].map(x => <option key={x}>{x.replaceAll("_", " ")}</option>)}</select><Input type="number" min="0" placeholder="Amount" value={amount} onChange={e => setAmount(e.target.value)} /><select className="border rounded px-3" value={mode} onChange={e => setMode(e.target.value)}>{["Cash", "Bank Transfer", "UPI", "Cheque", "Other"].map(x => <option key={x}>{x}</option>)}</select><Input placeholder="Reference / bill no." value={reference} onChange={e => setReference(e.target.value)} /><Input placeholder="Notes" value={entryNotes} onChange={e => setEntryNotes(e.target.value)} /><Button disabled={!partyId || !Number(amount)} onClick={submitDaily}>Save Daily Transaction</Button></div></Card>}
    {view === "daybook" && <Table title="Day Book" rows={book || []} columns={[["date", "Date"], ["type", "Transaction"], ["party", "Party"], ["reference", "Reference"], ["amount", "Amount"], ["mode", "Mode"]]} />}
    {["cash", "bank", "upi"].includes(view) && <Table title={`${view.toUpperCase()} Book`} rows={book?.rows || []} columns={[["date", "Date"], ["type", "Transaction"], ["party", "Party"], ["reference", "Reference"], ["receipt", "Receipt"], ["payment", "Payment"], ["balance", "Balance"]]} />}
    {view === "expenses" && <Table title="Expense Register" rows={expenses} columns={[["expense_date", "Date"], ["category", "Category"], ["classification", "Classification"], ["amount", "Amount"], ["payment_mode", "Mode"], ["invoice_no", "Invoice"]]} />}
    {view === "outstanding" && <Table title="Outstanding Balances" rows={outstanding} columns={[["party", "Party"], ["type", "Type"], ["direction", "Direction"], ["outstanding", "Amount"]]} />}
    {view === "ledger" && <><Card className="p-4 mb-5"><div className="grid grid-cols-1 md:grid-cols-4 gap-3"><select className="border rounded px-3" value={partyType} onChange={e => changeType(e.target.value)}><option value="CUSTOMER">Customer Ledger</option><option value="SUPPLIER">Supplier Ledger</option><option value="FABRICATOR">Fabricator Ledger</option><option value="WORKER">Worker Ledger</option></select><select className="border rounded px-3" value={partyId} onChange={e => setPartyId(e.target.value)}>{parties.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><Input type="month" value={month} onChange={e => setMonth(e.target.value)} /><Button variant="outline" onClick={() => window.print()}>Print / Save PDF</Button></div></Card><div className="grid grid-cols-1 md:grid-cols-3 gap-3 mb-5"><StatCard label="Opening balance" value={money(ledger?.opening_balance)} /><StatCard label={partyType === "CUSTOMER" ? "Outstanding" : "Payable balance"} value={money(ledger?.closing_balance)} /><StatCard label="Transactions" value={ledger?.rows.length || 0} /></div><Card className="p-4 mb-5"><div className="font-display font-semibold mb-3">{partyType === "CUSTOMER" ? "Receive Payment" : "Make Payment / Advance"}</div><div className="flex flex-wrap gap-2"><Input className="w-40" type="number" min="0" placeholder="Amount" value={amount} onChange={e => setAmount(e.target.value)} /><select className="border rounded px-3" value={mode} onChange={e => setMode(e.target.value)}>{["Cash", "Bank Transfer", "UPI", "Cheque", "Other"].map(x => <option key={x}>{x}</option>)}</select><Input className="w-44" placeholder="Reference no." value={reference} onChange={e => setReference(e.target.value)} /><Button disabled={!partyId || !Number(amount)} onClick={() => submit(partyType === "CUSTOMER" ? "PAYMENT_RECEIVED" : "PAYMENT")}>{partyType === "CUSTOMER" ? "Receive Payment" : "Make Payment"}</Button>{partyType !== "CUSTOMER" && <Button variant="outline" disabled={!partyId || !Number(amount)} onClick={() => submit("ADVANCE")}>Record Advance</Button>}</div></Card><Table title={`${ledger?.party_name || "Party"} Ledger`} rows={ledger?.rows || []} columns={[["date", "Date"], ["type", "Transaction"], ["reference", "Reference"], ["qty", "Qty"], ["rate", "Rate"], ["debit", "Debit"], ["credit", "Credit"], ["balance", "Balance"]]} /></>}
  </div>;
}
