import React, { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "@/lib/api";
import { PageHeader, Card, StatCard } from "@/components/Common";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";

const thisMonth = new Date().toISOString().slice(0, 7);
const money = (value) => `₹${Number(value || 0).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;
const dateOnly = (value) => value ? new Date(value).toLocaleDateString() : "—";

export default function Accounts() {
  const [month, setMonth] = useState(thisMonth), [view, setView] = useState("work");
  const [report, setReport] = useState({ rows: [], totals: {} }), [rates, setRates] = useState([]), [fabricators, setFabricators] = useState([]), [articles, setArticles] = useState([]);
  const [workType, setWorkType] = useState("CUTTING"), [fabricatorId, setFabricatorId] = useState(""), [articleId, setArticleId] = useState(""), [rate, setRate] = useState(""), [effectiveFrom, setEffectiveFrom] = useState(new Date().toISOString().slice(0, 10));

  const load = async () => {
    try {
      const [work, cards, fabs, articleList] = await Promise.all([api.get(`/accounts/production-work?month=${month}`), api.get("/accounts/rates"), api.get("/fabricators"), api.get("/articles")]);
      setReport(work); setRates(cards); setFabricators(fabs); setArticles(articleList); if (!fabricatorId && fabs[0]) setFabricatorId(fabs[0].id); if (!articleId && articleList[0]) setArticleId(articleList[0].id);
    } catch { setReport({ rows: [], totals: {} }); }
  };
  useEffect(() => { load(); }, [month]); // eslint-disable-line react-hooks/exhaustive-deps
  const partyId = workType === "STITCHING" ? fabricatorId : "FACTORY";
  const activeRate = useMemo(() => rates.find((card) => card.party_id === partyId && card.work_type === workType && card.article_id === articleId), [rates, partyId, workType, articleId]);
  const saveRate = async () => {
    if (!Number(rate) || Number(rate) < 0 || !articleId || (workType === "STITCHING" && !fabricatorId)) return toast.error("Select the article and enter a valid per-pair rate");
    try { await api.post("/accounts/rates", { party_id: partyId, article_id: articleId, work_type: workType, rate: Number(rate), effective_from: effectiveFrom }); toast.success("Article rate saved. New work uses it from the effective date."); setRate(""); load(); }
    catch (error) { toast.error(error.response?.data?.detail || "Could not save rate"); }
  };
  const total = Object.values(report.totals || {}).reduce((sum, item) => sum + (item.amount || 0), 0);
  const tabs = [["work", "Monthly Work Accounts"], ["rates", "Set Work Rates"], ["workflow", "Workflow"]];
  return <div data-testid="accounts-page">
    <PageHeader title="Production Accounts" subtitle="Monthly cutting, printing and stitching costs" actions={<Button asChild><Link to="/accounts/article-costing">Article-wise Costing</Link></Button>} />
    <div className="flex flex-wrap gap-2 mb-5">{tabs.map(([id, label]) => <Button key={id} size="sm" variant={view === id ? "default" : "outline"} onClick={() => setView(id)}>{label}</Button>)}</div>
    {view === "work" && <><Card className="p-3 mb-5 flex flex-wrap items-center gap-3"><label className="text-sm font-medium">Month</label><Input className="w-44" type="month" value={month} onChange={(event) => setMonth(event.target.value)} /><span className="text-xs text-slate-500">Entries are created automatically from the production workflow.</span></Card><div className="grid grid-cols-1 md:grid-cols-4 gap-3 mb-5"><StatCard label="Cutting" value={money(report.totals?.Cutting?.amount)} subtext={`${report.totals?.Cutting?.qty || 0} pairs`} /><StatCard label="Printing" value={money(report.totals?.Printing?.amount)} subtext={`${report.totals?.Printing?.qty || 0} pairs`} /><StatCard label="Stitching" value={money(report.totals?.Stitching?.amount)} subtext={`${report.totals?.Stitching?.qty || 0} good pairs`} /><StatCard label="Total work cost" value={money(total)} subtext="This month" /></div><Card className="overflow-x-auto"><div className="p-4 font-display font-semibold">Monthly Production Work Account</div><table className="data-table w-full"><thead><tr><th>Date</th><th>Process</th><th>Plan</th><th>Article / Colour</th><th>Worker / Fabricator</th><th>Pairs</th><th>Rate / Pair</th><th>Amount</th></tr></thead><tbody>{report.rows.map((row, index) => <tr key={`${row.process}-${row.plan_id}-${index}`}><td>{dateOnly(row.date)}</td><td>{row.process}</td><td className="font-mono">{row.plan_no}</td><td>{row.article_name} <span className="text-slate-500">{row.colour}</span></td><td>{row.party}</td><td>{row.qty}</td><td>{money(row.rate)}</td><td className="font-semibold">{money(row.amount)}</td></tr>)}{!report.rows.length && <tr><td colSpan="8" className="text-center text-slate-500 py-7">No production work was recorded in this month.</td></tr>}</tbody></table></Card></>}
    {view === "rates" && <div className="max-w-3xl space-y-5"><Card className="p-4"><div className="font-display font-semibold mb-1">Set Article-wise Rate per Pair</div><p className="text-sm text-slate-500 mb-4">Every article has its own Cutting and Printing rate. Stitching also varies by fabricator.</p><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><select className="border rounded px-3" value={articleId} onChange={(event) => setArticleId(event.target.value)}><option value="">Select article</option>{articles.map((article) => <option key={article.id} value={article.id}>{article.code} — {article.name}</option>)}</select><select className="border rounded px-3" value={workType} onChange={(event) => setWorkType(event.target.value)}><option value="CUTTING">Cutting</option><option value="PRINTING">Printing</option><option value="STITCHING">Stitching</option></select>{workType === "STITCHING" ? <select className="border rounded px-3" value={fabricatorId} onChange={(event) => setFabricatorId(event.target.value)}><option value="">Select fabricator</option>{fabricators.map((fab) => <option key={fab.id} value={fab.id}>{fab.name}</option>)}</select> : <div className="border rounded px-3 py-2 bg-slate-50 text-slate-600">Factory rate for selected article</div>}<Input type="number" min="0" step="0.01" placeholder="Rate per pair" value={rate} onChange={(event) => setRate(event.target.value)} /><Input type="date" value={effectiveFrom} onChange={(event) => setEffectiveFrom(event.target.value)} /><Button onClick={saveRate}>Save Article Rate</Button></div>{activeRate && <p className="text-xs text-slate-500 mt-3">Current listed rate: {money(activeRate.rate)} / pair from {activeRate.effective_from}</p>}</Card><Card className="overflow-x-auto"><div className="p-4 font-display font-semibold">Saved Article Rates</div><table className="data-table w-full"><thead><tr><th>Article</th><th>Process</th><th>Factory / Fabricator</th><th>Rate / Pair</th><th>Effective From</th></tr></thead><tbody>{rates.map((card) => <tr key={card.id}><td>{articles.find((article) => article.id === card.article_id)?.name || "All articles (old rate)"}</td><td>{card.work_type}</td><td>{card.party_id === "FACTORY" ? "Factory" : fabricators.find((fab) => fab.id === card.party_id)?.name || "Fabricator"}</td><td>{money(card.rate)}</td><td>{card.effective_from}</td></tr>)}{!rates.length && <tr><td colSpan="5" className="text-center text-slate-500 py-6">No rates configured.</td></tr>}</tbody></table></Card></div>}
    {view === "workflow" && <Card className="p-5 max-w-3xl"><div className="font-display font-semibold mb-4">Production Costing Workflow</div><ol className="space-y-4 text-sm"><li><strong>1. Set rates:</strong> Enter per-pair Cutting and Printing factory rates, then a Stitching rate for each fabricator.</li><li><strong>2. Start Cutting:</strong> The plan quantity appears in the Cutting account for that month.</li><li><strong>3. Issue to Printing:</strong> The plan quantity appears in the Printing account for that month.</li><li><strong>4. Receive Stitching:</strong> Accepted good pairs appear in the Stitching account using the fabricator rate.</li><li><strong>5. Pass QC:</strong> QC-passed output receives material, cutting, printing and stitching costs in Article-wise Costing.</li></ol><Button className="mt-5" asChild><Link to="/accounts/article-costing">Open Article-wise Costing</Link></Button></Card>}
  </div>;
}
