import React, { useRef, useState } from "react";
import client from "@/lib/api";
import { PageHeader, Card } from "@/components/Common";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export default function Assistant() {
  const [message, setMessage] = useState(""), [messages, setMessages] = useState([]), [busy, setBusy] = useState(false); const fileRef = useRef();
  const confirm = async (action, index) => { if (busy) return; setBusy(true); try { const { data } = await client.post("/assistant/confirm", { action_type: action.type, data: action.data }); setMessages(x => x.map((m, i) => i === index ? { ...m, confirmed: `Confirmed: ${data.action_type}` } : m)); } catch (e) { setMessages(x => x.map((m, i) => i === index ? { ...m, error: e.response?.data?.detail || "Could not complete the action." } : m)); } finally { setBusy(false); } };
  const ask = async () => { if (!message.trim() || busy) return; const text = message; const history = messages.slice(-12).map(m => ({ role: m.role === "Assistant" ? "assistant" : "user", text: m.text })); setMessage(""); setMessages(x => [...x, { role: "You", text }]); setBusy(true); try { const { data } = await client.post("/assistant/chat", { message: text, history }); setMessages(x => [...x, { role: "Assistant", text: data.reply, action: data.proposed_action }]); } catch (e) { setMessages(x => [...x, { role: "Assistant", text: e.response?.data?.detail || "Assistant is unavailable." }]); } finally { setBusy(false); } };
  const scan = async (event) => { const file = event.target.files?.[0]; if (!file) return; const form = new FormData(); form.append("file", file); setMessages(x => [...x, { role: "You", text: `Uploaded bill: ${file.name}` }]); setBusy(true); try { const { data } = await client.post("/assistant/purchase-bill", form, { headers: { "Content-Type": "multipart/form-data" } }); setMessages(x => [...x, { role: "Assistant", text: data.reply, action: data.proposed_action }]); } catch (e) { setMessages(x => [...x, { role: "Assistant", text: e.response?.data?.detail || "Bill could not be read." }]); } finally { setBusy(false); event.target.value = ""; } };
  return <div data-testid="assistant-page"><PageHeader title="Factory AI Assistant" subtitle="Ask questions, draft transactions, or upload a purchase bill for review" actions={<><input ref={fileRef} className="hidden" type="file" accept="image/*,.pdf" onChange={scan} /><Button variant="outline" onClick={() => fileRef.current?.click()}>Upload Purchase Bill</Button></>} /><Card className="p-4 max-w-4xl"><div className="min-h-80 space-y-3 mb-4">{messages.length === 0 && <div className="text-slate-500 text-sm">Try: “Record ₹2,500 electricity expense paid by UPI”, “start cutting plan P-0001”, or ask for a fabricator return. Every changing action needs your final confirmation.</div>}{messages.map((m, i) => <div key={i} className={m.role === "You" ? "text-right" : "text-left"}><div className={`inline-block max-w-[85%] rounded-lg px-3 py-2 text-sm ${m.role === "You" ? "bg-blue-600 text-white" : "bg-slate-100"}`}><div className="font-semibold text-xs mb-1">{m.role}</div><div className="whitespace-pre-wrap">{m.text}</div>{m.action && !m.confirmed && <><pre className="mt-2 text-left text-xs whitespace-pre-wrap border-t pt-2">Review action: {JSON.stringify(m.action, null, 2)}</pre><Button className="mt-2" size="sm" disabled={busy} onClick={() => confirm(m.action, i)}>Confirm & Execute</Button></>}{m.confirmed && <div className="mt-2 text-green-700 font-semibold">{m.confirmed}</div>}{m.error && <div className="mt-2 text-red-700">{m.error}</div>}</div></div>)}{busy && <div className="text-sm text-slate-500">Working…</div>}</div><div className="flex gap-2"><Input value={message} onChange={e => setMessage(e.target.value)} onKeyDown={e => e.key === "Enter" && ask()} placeholder="Ask the factory assistant…" /><Button disabled={busy || !message.trim()} onClick={ask}>Send</Button></div></Card></div>;
}
