import React, { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "@/lib/api";
import { PageHeader, Card, StatCard, StatusBadge } from "@/components/Common";
import { Button } from "@/components/ui/button";

const pct = (v) => v == null ? "—" : `${v}%`;
const date = (v) => v ? new Date(v).toLocaleDateString() : "—";

export default function Fabricators() {
  const [items, setItems] = useState([]), [selectedId, setSelectedId] = useState(null), [search, setSearch] = useState(""), [status, setStatus] = useState("ALL"), [month, setMonth] = useState(""), [tab, setTab] = useState("current");
  useEffect(() => {
    const legacyShape = (row) => ({
      ...row, plans_out: row.current_work || 0, pairs_out: row.pending_pairs || 0,
      returned_this_month: row.pairs_returned || 0, average_quality: null,
      on_time_return_pct: 0, rework_rate: row.rework_pairs && row.pairs_returned ? Number((row.rework_pairs / row.pairs_returned * 100).toFixed(1)) : 0,
      average_return_days: row.turnaround_days, overdue_plans: row.overdue_plans || 0,
      status: row.overdue_plans ? "Overdue" : ((row.current_work || 0) ? "Active" : "Clear"), overall: "Available after QC history",
      current_work: [], return_history: [], quality_history: [], defects: {}, completed_plans: row.returns || 0, completed_pairs: row.pairs_returned || 0,
    });
    api.get("/fabricators/control").catch(() => api.get("/fabricators/management").then((rows) => rows.map(legacyShape))).then((rows) => { setItems(rows); setSelectedId(rows[0]?.id || null); }).catch(() => setItems([]));
  }, []);
  const shown = useMemo(() => items.filter((f) => (status === "ALL" || f.status === status) && f.name.toLowerCase().includes(search.toLowerCase())), [items, status, search]);
  const selected = items.find((f) => f.id === selectedId);
  const byMonth = (rows, field) => rows.filter((r) => !month || (r[field] || "").slice(0, 7) === month);
  const current = selected?.current_work || [], returns = byMonth(selected?.return_history || [], "return_date"), quality = byMonth(selected?.quality_history || [], "date");
  const totals = { outsidePlans: items.reduce((n, f) => n + f.plans_out, 0), outsidePairs: items.reduce((n, f) => n + f.pairs_out, 0), overdue: items.reduce((n, f) => n + f.overdue_plans, 0), quality: items.filter((f) => f.average_quality != null).map((f) => f.average_quality) };
  const averageQuality = totals.quality.length ? (totals.quality.reduce((a, b) => a + b, 0) / totals.quality.length).toFixed(1) : "—";
  return <div data-testid="fabricators-page"><PageHeader title="Fabricators" subtitle="Stitching work, returns and quality performance" />
    <div className="grid grid-cols-2 lg:grid-cols-6 gap-3 mb-5"><StatCard label="Total Fabricators" value={items.length} /><StatCard label="Active Fabricators" value={items.filter((f) => f.active).length} /><StatCard label="Plans Outside" value={totals.outsidePlans} /><StatCard label="Pairs Outside" value={totals.outsidePairs} /><StatCard label="Overdue Plans" value={totals.overdue} /><StatCard label="Avg Quality" value={averageQuality === "—" ? "—" : `${averageQuality}%`} /></div>
    <Card className="p-4 mb-5"><div className="flex flex-wrap gap-3 items-end"><div><label className="text-sm font-medium">Search fabricator</label><input className="block border rounded px-3 py-2 mt-1" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Name" /></div><div><label className="text-sm font-medium">Status</label><select className="block border rounded px-3 py-2 mt-1" value={status} onChange={(e) => setStatus(e.target.value)}><option value="ALL">All statuses</option>{["Clear", "Active", "Attention Required", "Overdue"].map((x) => <option key={x}>{x}</option>)}</select></div><div><label className="text-sm font-medium">History month</label><input className="block border rounded px-3 py-2 mt-1" type="month" value={month} onChange={(e) => setMonth(e.target.value)} /></div></div></Card>
    <Card className="overflow-x-auto mb-5"><table className="data-table w-full"><thead><tr><th>Fabricator</th><th>Plans Out</th><th>Pairs Out</th><th>Returned This Month</th><th>Average Quality</th><th>Avg Return Time</th><th>Rework Rate</th><th>Overdue</th><th>Status</th><th></th></tr></thead><tbody>{shown.map((f) => <tr key={f.id}><td className="font-semibold">{f.name}</td><td>{f.plans_out}</td><td>{f.pairs_out}</td><td>{f.returned_this_month}</td><td>{pct(f.average_quality)}</td><td>{f.average_return_days == null ? "—" : `${f.average_return_days} days`}</td><td>{pct(f.rework_rate)}</td><td>{f.overdue_plans}</td><td><StatusBadge status={f.status} /></td><td><Button size="sm" variant="outline" onClick={() => setSelectedId(f.id)}>View</Button></td></tr>)}{!shown.length && <tr><td colSpan="10" className="text-center py-6 text-slate-500">No fabricators match.</td></tr>}</tbody></table></Card>
    <Card className="overflow-x-auto mb-5"><div className="p-4 font-display font-semibold">Fabricator Comparison <span className="text-xs font-normal text-slate-500">(ranking begins after 5 completed QC records)</span></div><table className="data-table w-full"><thead><tr><th>Fabricator</th><th>Pairs Completed</th><th>Quality</th><th>On-Time</th><th>Rework</th><th>Overall</th></tr></thead><tbody>{shown.map((f) => <tr key={f.id}><td>{f.name}</td><td>{f.completed_pairs}</td><td>{pct(f.average_quality)}</td><td>{pct(f.on_time_return_pct)}</td><td>{pct(f.rework_rate)}</td><td>{f.overall}</td></tr>)}</tbody></table></Card>
    {selected && <Card className="p-4"><div className="flex flex-wrap justify-between gap-3 mb-4"><div><div className="font-display font-semibold text-lg">Fabricator: {selected.name}</div><div className="text-sm text-slate-500">Quality and stitching history from real returns and QC records.</div></div><div className="flex gap-2">{[["current", "Current Work"], ["returns", "Return History"], ["quality", "Quality"], ["ledger", "Ledger"]].map(([id, label]) => <Button key={id} size="sm" variant={tab === id ? "default" : "outline"} onClick={() => setTab(id)}>{label}</Button>)}</div></div>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-5"><StatCard label="Current Pairs Outside" value={selected.pairs_out} /><StatCard label="Completed Pairs" value={selected.completed_pairs} /><StatCard label="Quality Score" value={pct(selected.average_quality)} /><StatCard label="On-Time Return" value={pct(selected.on_time_return_pct)} /><StatCard label="Rework" value={pct(selected.rework_rate)} /><StatCard label="Overdue" value={selected.overdue_plans} /></div>
      {tab === "current" && <table className="data-table w-full"><thead><tr><th>Plan</th><th>Article</th><th>Colour</th><th>Qty</th><th>Issue Date / Time</th><th>Days Outside</th><th>Status</th></tr></thead><tbody>{current.map((r) => <tr key={r.plan_id} className={r.overdue ? "bg-red-50" : ""}><td><Link className="text-blue-600 font-mono" to={`/production/${r.plan_id}`}>{r.plan_no}</Link></td><td>{r.article}</td><td>{r.colour}</td><td>{r.qty}</td><td>{r.issue_date ? new Date(r.issue_date).toLocaleString() : "—"}</td><td className={r.overdue ? "text-red-700 font-semibold" : ""}>{r.days_outside}</td><td><StatusBadge status={r.overdue ? "OVERDUE" : r.status} /></td></tr>)}{!current.length && <tr><td colSpan="7" className="text-center py-6 text-slate-500">No plans currently outside.</td></tr>}</tbody></table>}
      {tab === "returns" && <table className="data-table w-full"><thead><tr><th>Return Date</th><th>Plan</th><th>Article</th><th>Colour</th><th>Qty</th><th>Issue Date</th><th>Time Taken</th><th>QC Result</th><th>QC Score</th></tr></thead><tbody>{returns.map((r, i) => <tr key={i}><td>{date(r.return_date)}</td><td>{r.plan_no}</td><td>{r.article}</td><td>{r.colour}</td><td>{r.quantity}</td><td>{date(r.issue_date)}</td><td>{r.time_taken == null ? "—" : `${r.time_taken} days`}</td><td>{r.qc_result}</td><td>{pct(r.qc_score)}</td></tr>)}</tbody></table>}
      {tab === "quality" && <><table className="data-table w-full"><thead><tr><th>Plan</th><th>Date</th><th>Article</th><th>Colour</th><th>Qty</th><th>QC Score</th><th>QC Result</th><th>Defects</th><th>Rework</th></tr></thead><tbody>{quality.map((q, i) => <tr key={i}><td>{q.plan_no}</td><td>{date(q.date)}</td><td>{q.article}</td><td>{q.colour}</td><td>{q.quantity}</td><td>{pct(q.qc_score)}</td><td>{q.qc_result}</td><td>{q.defect_count}</td><td>{q.rework_required ? "Yes" : "No"}</td></tr>)}</tbody></table><div className="mt-4 text-sm"><strong>Defect analysis:</strong> {Object.entries(selected.defects || {}).map(([name, count]) => `${name}: ${count}`).join(" · ") || "No defects recorded."}</div></>}
      {tab === "ledger" && <table className="data-table w-full"><thead><tr><th>Date</th><th>Plan</th><th>Article</th><th>Colour</th><th>Qty</th><th>Stitching Out</th><th>Stitching Return</th><th>QC Result</th><th>QC Score</th></tr></thead><tbody>{returns.map((r, i) => <tr key={i}><td>{date(r.return_date)}</td><td>{r.plan_no}</td><td>{r.article}</td><td>{r.colour}</td><td>{r.quantity}</td><td>{date(r.issue_date)}</td><td>{date(r.return_date)}</td><td>{r.qc_result}</td><td>{pct(r.qc_score)}</td></tr>)}</tbody></table>}
    </Card>}
  </div>;
}
